export const SEED_EXERCISES = [

  // ─── CHEST ────────────────────────────────────────────────────────────────
  {
    name: 'Bench Press', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'A foundational upper-body push exercise targeting the chest, shoulders, and triceps.',
    instructions: ['Lie flat on the bench with feet firmly on the floor.','Grip the bar slightly wider than shoulder-width with an overhand grip.','Unrack the bar and hold directly above your chest with arms fully extended.','Slowly lower the bar to your mid-chest in a controlled manner.','Press the bar back up explosively until arms are fully extended.','Keep your back slightly arched and shoulder blades retracted throughout.'],
    tips: ['Keep wrists straight — avoid letting them bend backward.','Drive your feet into the floor for a stable base.','Do not bounce the bar off your chest — control the descent.','Breathe in on the way down, breathe out on the way up.'],
    commonMistakes: ['Flaring elbows too wide — keep them at 45–75 degrees.','Lifting hips off the bench.','Using too much weight before mastering form.'],
  },
  {
    name: 'Push-up', muscleGroup: 'Chest', equipment: 'None', difficulty: 'Beginner',
    description: 'A classic bodyweight exercise that builds chest, shoulder, and tricep strength anywhere.',
    instructions: ['Start in a high plank with hands slightly wider than shoulder-width.','Keep your body in a straight line from head to heels.','Lower your chest toward the floor by bending your elbows.','Stop when your chest is about an inch from the ground.','Push back up explosively to the starting position.','Squeeze your chest at the top of each rep.'],
    tips: ['Engage your core — do not let your hips sag.','Look slightly ahead to keep your neck neutral.','Wider hands = more chest; closer hands = more triceps.'],
    commonMistakes: ['Sagging hips — keep the body rigid.','Partial range of motion.','Flaring elbows at 90 degrees — keep at 45 degrees.'],
  },
  {
    name: 'Dumbbell Flyes', muscleGroup: 'Chest', equipment: 'Dumbbells', difficulty: 'Intermediate',
    description: 'An isolation exercise that stretches and contracts the chest through a wide arc.',
    instructions: ['Lie on a flat bench holding dumbbells above your chest, palms facing each other.','Slightly bend your elbows and maintain that angle throughout.','Lower dumbbells out to the sides in a wide arc until you feel a chest stretch.','Bring the dumbbells back up in the same arc, squeezing your chest at the top.','Imagine hugging a large tree throughout the movement.'],
    tips: ['Use lighter weight — this is an isolation movement.','Feel the stretch in your chest at the bottom.','Keep a soft bend in the elbows to protect the joint.'],
    commonMistakes: ['Straightening the arms completely.','Going too heavy and losing control.','Not getting a full stretch at the bottom.'],
  },
  {
    name: 'Incline Press', muscleGroup: 'Chest', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'A bench press variation on an inclined bench targeting the upper chest.',
    instructions: ['Set the bench to a 30–45 degree incline.','Grip the bar slightly wider than shoulder-width.','Unrack the bar and hold above your upper chest.','Lower the bar to your upper chest in a controlled motion.','Press back up until arms are fully extended.','Keep your back flat against the bench throughout.'],
    tips: ['A 30–45 degree angle is optimal — too steep shifts work to shoulders.','Keep shoulder blades pinched together for stability.'],
    commonMistakes: ['Setting the bench too steep (above 45 degrees).','Losing upper back contact with the bench.'],
  },
  {
    name: 'Cable Crossover', muscleGroup: 'Chest', equipment: 'Cable Machine', difficulty: 'Intermediate',
    description: 'A cable isolation exercise for the chest providing constant tension throughout the movement.',
    instructions: ['Set the cable pulleys at shoulder height or slightly above.','Stand in the center, grip both handles, and step slightly forward.','Begin with arms wide and a soft bend in the elbows.','Bring both hands together in front of your chest in a hugging arc.','Squeeze your chest hard at the center.','Slowly return to the starting position with control.'],
    tips: ['The constant cable tension makes this more effective than dumbbells for isolation.','Try different pulley heights to hit upper, mid, or lower chest.','Focus on the squeeze, not the weight used.'],
    commonMistakes: ['Using too much weight and losing the arc.','Straightening elbows fully.','Leaning too far forward and losing stability.'],
  },
  {
    name: 'Chest Dip', muscleGroup: 'Chest', equipment: 'Dip Bars', difficulty: 'Intermediate',
    description: 'A bodyweight compound movement heavily targeting the lower chest when performed with a forward lean.',
    instructions: ['Grip the dip bars and support your body at arm length.','Lean your torso forward at 30–45 degrees throughout the movement.','Lower yourself by bending your elbows until you feel a deep chest stretch.','Pause briefly at the bottom.','Push back up to the starting position, maintaining the forward lean.'],
    tips: ['Lean forward to target chest — staying upright targets triceps.','Add weight with a dip belt once bodyweight is easy.','Control the descent to maximize muscle activation.'],
    commonMistakes: ['Going too deep and straining the shoulder joint.','Not leaning forward enough to engage the chest.','Flaring elbows outward.'],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  {
    name: 'Pull-up', muscleGroup: 'Back', equipment: 'Pull-up Bar', difficulty: 'Intermediate',
    description: 'One of the best upper-body exercises for building lat width and overall back strength.',
    instructions: ['Hang from the bar with an overhand grip, hands slightly wider than shoulder-width.','Start from a dead hang with arms fully extended.','Engage your core and pull your shoulder blades down and back.','Drive your elbows toward the floor as you pull your chin above the bar.','Slowly lower yourself back to a dead hang.'],
    tips: ['Think about pulling the bar down to you, not pulling yourself up.','Avoid kipping — use strict form for best results.','Use a resistance band for assistance if needed.','Squeeze your lats at the top of each rep.'],
    commonMistakes: ['Not going to a full dead hang at the bottom.','Using momentum and swinging the body.','Shrugging shoulders up instead of pulling shoulder blades down.'],
  },
  {
    name: 'Deadlift', muscleGroup: 'Back', equipment: 'Barbell', difficulty: 'Advanced',
    description: 'The king of all exercises — a full-body compound lift that builds total strength.',
    instructions: ['Stand with feet hip-width apart, bar over mid-foot.','Hinge at the hips and grip the bar just outside your legs.','Take a deep breath and brace your core tightly.','Push the floor away rather than pulling the bar up.','Keep the bar close to your body as you stand tall.','Lock out your hips and knees simultaneously at the top.','Lower the bar back down with control by hinging at the hips first.'],
    tips: ['Keep the bar as close to your body as possible.','Brace your core like you are about to take a punch.','Keep your chest up and back flat — never round the lower back.','Start light and prioritize form above all else.'],
    commonMistakes: ['Rounding the lower back — the most dangerous mistake.','Jerking the bar off the floor.','Bar drifting away from the body.','Looking up too aggressively.'],
  },
  {
    name: 'Lat Pulldown', muscleGroup: 'Back', equipment: 'Cable Machine', difficulty: 'Beginner',
    description: 'A great beginner exercise to build lat strength before progressing to pull-ups.',
    instructions: ['Sit at the machine and adjust the thigh pad to secure your legs.','Grip the bar wider than shoulder-width with an overhand grip.','Lean back slightly — about 10–15 degrees.','Pull the bar down to your upper chest by driving elbows toward the floor.','Squeeze your lats hard at the bottom.','Slowly return the bar to the starting position with arms fully extended.'],
    tips: ['Focus on pulling with your elbows, not your hands.','Full extension at the top is important for lat stretch.'],
    commonMistakes: ['Pulling the bar behind the neck — dangerous for the cervical spine.','Leaning back too far and turning it into a row.','Not getting full range of motion at the top.'],
  },
  {
    name: 'Bent-over Row', muscleGroup: 'Back', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'A compound rowing movement that builds thickness in the mid and upper back.',
    instructions: ['Stand with feet hip-width apart, holding the barbell with an overhand grip.','Hinge at the hips until your torso is roughly 45 degrees to the floor.','Let the bar hang straight down with arms extended.','Pull the bar into your lower chest/upper abdomen by driving elbows back.','Squeeze your shoulder blades together at the top.','Lower the bar back down with control.'],
    tips: ['Maintain a flat back throughout — do not round the spine.','Drive your elbows back as far as possible for full range.'],
    commonMistakes: ['Rounding the lower back under heavy load.','Using too much body momentum to swing the bar up.'],
  },
  {
    name: 'Seated Cable Row', muscleGroup: 'Back', equipment: 'Cable Machine', difficulty: 'Beginner',
    description: 'A beginner-friendly back exercise building thickness in the middle and lower back.',
    instructions: ['Sit at the cable row machine with feet on the platform and knees slightly bent.','Grip the handle with both hands, arms fully extended.','Sit upright — do not hunch forward.','Pull the handle into your lower abdomen by driving your elbows back.','Squeeze your shoulder blades together at the end of the pull.','Slowly extend your arms back to the start, allowing a stretch in your lats.'],
    tips: ['Keep your torso upright — do not sway back and forth.','The squeeze at the end is where all the muscle activation happens.','Try different handles — wide, narrow, or rope — to hit different back muscles.'],
    commonMistakes: ['Using body momentum to rock back and pull.','Rounding the back as the arms extend.','Not achieving full range of motion in both directions.'],
  },
  {
    name: 'Single-arm Dumbbell Row', muscleGroup: 'Back', equipment: 'Dumbbells', difficulty: 'Intermediate',
    description: 'A unilateral back exercise for building lat and mid-back thickness with full range of motion.',
    instructions: ['Place one knee and the same-side hand on a bench for support.','Hold a dumbbell in the opposite hand with arm hanging straight down.','Pull the dumbbell up and back toward your hip.','Drive your elbow as far behind your body as possible.','Lower the dumbbell back to a full hang.','Complete all reps on one side before switching.'],
    tips: ['Think of your arm as a hook — let your back do the work.','Allow a full stretch at the bottom to maximize range of motion.','Drive the elbow back, not just up.'],
    commonMistakes: ['Rotating the torso to help lift the weight.','Not getting full range at the top and bottom.','Using too much arm and not enough back.'],
  },
  {
    name: 'Face Pull', muscleGroup: 'Back', equipment: 'Cable Machine', difficulty: 'Beginner',
    description: 'Essential exercise for rear deltoids, rotator cuff health, and posture correction.',
    instructions: ['Set the cable pulley to face height or slightly above.','Grip the rope attachment with both hands, thumbs facing you.','Step back and pull the rope toward your face, separating your hands.','Drive your elbows wide and back — finish with hands beside your ears.','Squeeze your rear delts and upper back at the peak.','Slowly return to the starting position.'],
    tips: ['This exercise is critical for shoulder health and posture — do it often.','Keep elbows high throughout the pull.','Use a lighter weight and focus on the squeeze.'],
    commonMistakes: ['Pulling too low and targeting the wrong muscles.','Rushing through reps without squeezing.','Using too much weight and losing control.'],
  },
  {
    name: 'T-bar Row', muscleGroup: 'Back', equipment: 'Barbell', difficulty: 'Advanced',
    description: 'A heavy compound back exercise targeting the entire back with great overload potential.',
    instructions: ['Straddle a barbell anchored in a corner or landmine attachment.','Grip the bar with both hands close together.','Hinge at the hips to a 45-degree torso angle, back flat.','Pull the bar up toward your chest, driving elbows straight back.','Squeeze your shoulder blades together hard at the top.','Lower the bar with control to a full hang.'],
    tips: ['Keep your chest tall and back flat — never let your lower back round.','The movement is very similar to a bent-over row but allows heavier loading.'],
    commonMistakes: ['Rounding the lower back under heavy load.','Not getting a full stretch at the bottom.','Using body swing to help with the lift.'],
  },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────
  {
    name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'The primary overhead pressing movement for building shoulder size and strength.',
    instructions: ['Stand with feet shoulder-width apart, bar resting on your upper chest.','Grip the bar just outside shoulder-width.','Brace your core and glutes before pressing.','Press the bar straight up while slightly tilting your head back.','Lock out your elbows at the top and shrug your shoulders up.','Lower the bar back to your upper chest with control.'],
    tips: ['Keep your core tight — do not arch your lower back.','Press in a straight vertical line.','Shrug your traps up at the top for full lockout.'],
    commonMistakes: ['Excessive lower back arch.','Pressing in front of the body instead of straight up.'],
  },
  {
    name: 'Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'An isolation exercise targeting the lateral deltoid for wider, rounder shoulders.',
    instructions: ['Stand with a dumbbell in each hand at your sides.','Keep a slight bend in your elbows throughout.','Raise both arms out to the sides until parallel with the floor.','Lead with your elbows, not your hands.','Pause briefly at the top, then slowly lower back down.'],
    tips: ['Use lighter weight and focus on feeling the side shoulder.','Tilt the dumbbells slightly so the pinky side is higher.','Avoid shrugging your traps — keep shoulders down.'],
    commonMistakes: ['Using too much weight and swinging the body.','Raising the dumbbells above shoulder height.','Shrugging the shoulders up during the raise.'],
  },
  {
    name: 'Front Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'Targets the anterior (front) deltoid with a forward lifting motion.',
    instructions: ['Stand holding dumbbells in front of your thighs, palms facing down.','Keep a slight bend in the elbows.','Raise one or both arms forward to shoulder height.','Pause briefly at the top.','Slowly lower back to the starting position.'],
    tips: ['Keep the movement strict and controlled.','Keep your torso still and upright.'],
    commonMistakes: ['Swinging the body to lift the weight.','Going above shoulder height.'],
  },
  {
    name: 'Arnold Press', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'Intermediate',
    description: 'A complete shoulder exercise popularized by Arnold Schwarzenegger that hits all three deltoid heads.',
    instructions: ['Sit on a bench holding dumbbells at shoulder height, palms facing you.','As you press upward, rotate your palms to face forward.','Reach full extension at the top with palms facing away.','Reverse the rotation as you lower the dumbbells back to the start.','The rotation covers the full range of shoulder motion.'],
    tips: ['The rotation is the key — do it smoothly, not jerkily.','Keep your core tight to avoid lower back strain.','Excellent all-in-one shoulder movement.'],
    commonMistakes: ['Rotating too fast and losing control.','Using too much weight and shortening the range of motion.'],
  },
  {
    name: 'Rear Delt Fly', muscleGroup: 'Shoulders', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'Isolates the rear deltoid — a commonly underdeveloped muscle essential for posture and shoulder balance.',
    instructions: ['Sit at the edge of a bench and hinge forward until your chest is near your thighs.','Hold a dumbbell in each hand hanging below you, palms facing each other.','With a slight bend in the elbows, raise both arms out to the sides.','Lead with your elbows and squeeze your rear delts at the top.','Slowly lower the dumbbells back to the starting position.'],
    tips: ['Keep the movement slow and controlled — this muscle is small.','Do not rotate your wrists during the movement.','Think of bending the bar behind you, not just raising your arms.'],
    commonMistakes: ['Going too heavy and using momentum.','Raising arms too high — stop at shoulder height.','Pulling with the traps instead of the rear delts.'],
  },
  {
    name: 'Upright Row', muscleGroup: 'Shoulders', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'A compound exercise building the lateral delts and upper traps.',
    instructions: ['Stand holding a barbell in front of your thighs with an overhand grip, hands shoulder-width.','Pull the bar straight up toward your chin.','Lead with your elbows — they should be higher than your wrists at the top.','Stop when the bar reaches chin height.','Lower the bar back down with control.'],
    tips: ['A wider grip is more shoulder-friendly and shifts work to the lateral delts.','Keep the bar close to your body throughout.'],
    commonMistakes: ['Using a narrow grip which can impinge the shoulder.','Raising the bar too high past the chin.'],
  },

  // ─── ARMS ─────────────────────────────────────────────────────────────────
  {
    name: 'Bicep Curl', muscleGroup: 'Arms', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'The classic arm exercise for building bicep size and strength.',
    instructions: ['Stand holding dumbbells at your sides, palms facing forward.','Keep your elbows pinned close to your torso throughout.','Curl the dumbbells upward toward your shoulders by contracting the biceps.','Squeeze hard at the top of the movement.','Slowly lower the dumbbells back to the starting position.'],
    tips: ['Slow the lowering portion to 3 counts for more activation.','Fully extend your arms at the bottom for maximum range.','Supinate your wrists as you curl for peak contraction.'],
    commonMistakes: ['Swinging the body to help lift the weight.','Not fully extending the arms at the bottom.'],
  },
  {
    name: 'Tricep Dip', muscleGroup: 'Arms', equipment: 'Dip Bars', difficulty: 'Intermediate',
    description: 'A bodyweight compound movement targeting the triceps, chest, and shoulders.',
    instructions: ['Grip the parallel bars and support your body with straight arms.','Cross your ankles behind you and lean slightly forward.','Lower your body by bending your elbows until upper arms are parallel to the floor.','Keep elbows pointing backward, not flaring out.','Push back up to the starting position.'],
    tips: ['Lean forward to emphasize chest; stay upright for more tricep focus.','Do not go below 90 degrees to protect the shoulder joint.'],
    commonMistakes: ['Going too deep and straining the shoulders.','Flaring elbows out to the sides.'],
  },
  {
    name: 'Hammer Curl', muscleGroup: 'Arms', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'A curl variation with a neutral grip targeting the brachialis and brachioradialis for arm thickness.',
    instructions: ['Hold dumbbells at your sides with a neutral grip (palms facing each other).','Keep your elbows close to your torso.','Curl the dumbbells upward without rotating your wrists.','Squeeze at the top.','Lower slowly back to the starting position.'],
    tips: ['Great exercise for building arm thickness.','Can be done alternating or both arms at once.'],
    commonMistakes: ['Rotating the wrist during the movement — keep it neutral.','Using too much momentum.'],
  },
  {
    name: 'Skull Crusher', muscleGroup: 'Arms', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'An overhead tricep extension that fully stretches and contracts the triceps.',
    instructions: ['Lie on a bench holding a barbell above your chest, arms extended.','Keep your upper arms vertical and perpendicular to the floor.','Bend only at the elbows, lowering the bar toward your forehead.','Stop just before the bar touches your head.','Extend your elbows back to the starting position.'],
    tips: ['Move ONLY at the elbow — upper arms stay fixed.','Use a controlled tempo on the way down.','An EZ bar reduces wrist strain.'],
    commonMistakes: ['Letting upper arms drift — they must stay vertical.','Going too heavy and losing control near your head.'],
  },
  {
    name: 'Tricep Rope Pushdown', muscleGroup: 'Arms', equipment: 'Cable Machine', difficulty: 'Beginner',
    description: 'The most common and effective cable exercise for isolating all three heads of the triceps.',
    instructions: ['Attach a rope to a high cable pulley.','Stand facing the machine and grip the rope with both hands.','Pin your elbows to your sides — they stay fixed throughout.','Push the rope down and slightly outward until arms are fully extended.','Spread the rope handles apart at the bottom for a stronger tricep squeeze.','Slowly return to the starting position.'],
    tips: ['Keep elbows locked to your sides — this is the key to isolating the triceps.','Spreading the rope at the bottom significantly increases the contraction.','Full lockout at the bottom is important — do not stop short.'],
    commonMistakes: ['Letting the elbows flare out or drift forward.','Using the chest and shoulders to help push.','Not achieving full extension.'],
  },
  {
    name: 'Overhead Tricep Extension', muscleGroup: 'Arms', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'An isolation movement that targets the long head of the tricep with a full overhead stretch.',
    instructions: ['Sit or stand holding one dumbbell with both hands above your head.','Keep your upper arms close to your ears and vertical.','Lower the dumbbell behind your head by bending at the elbows only.','Feel the stretch in the back of your arms.','Extend your elbows to raise the dumbbell back to the starting position.'],
    tips: ['The long head of the tricep only gets fully stretched in the overhead position.','Keep elbows pointed forward — do not let them flare out.','Use a moderate weight and focus on the full stretch.'],
    commonMistakes: ['Letting elbows flare outward.','Using too much weight and losing control behind the head.','Not getting the full stretch at the bottom.'],
  },
  {
    name: 'Preacher Curl', muscleGroup: 'Arms', equipment: 'Barbell', difficulty: 'Beginner',
    description: 'A bicep curl variation using a preacher bench to eliminate swinging and isolate the biceps.',
    instructions: ['Sit at a preacher bench and rest your upper arms on the pad.','Grip the bar with an underhand grip at shoulder width.','Let the bar hang down with arms nearly fully extended.','Curl the bar upward by contracting the biceps.','Squeeze hard at the top.','Slowly lower to the starting position — do not fully lock out to keep tension on the muscle.'],
    tips: ['The pad eliminates body swing, forcing the biceps to do all the work.','Use a slow, controlled negative (lowering phase).'],
    commonMistakes: ['Lowering the weight too fast.','Using momentum by jerking the elbows off the pad.'],
  },
  {
    name: 'Concentration Curl', muscleGroup: 'Arms', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'A strict isolation curl performed seated for maximum bicep peak contraction.',
    instructions: ['Sit on a bench with your legs spread.','Rest your right elbow on the inside of your right thigh.','Hold a dumbbell with your arm fully extended.','Curl the dumbbell up toward your chest, squeezing hard at the top.','Slowly lower back to the starting position.','Complete all reps then switch arms.'],
    tips: ['This is one of the best exercises for peak bicep contraction.','Keep your elbow braced against your leg — it should not move.'],
    commonMistakes: ['Letting the elbow swing off the leg.','Not achieving full range of motion.'],
  },
  {
    name: 'Close-grip Bench Press', muscleGroup: 'Arms', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'A bench press variation with a narrow grip that shifts emphasis to the triceps.',
    instructions: ['Lie flat on the bench and grip the bar with hands about shoulder-width apart.','Unrack the bar and hold above your lower chest.','Lower the bar to your lower chest with elbows tucked close to your sides.','Press back up to the starting position.','Keep elbows tracking inward — not flared.'],
    tips: ['Slightly narrower than shoulder-width is optimal — hands touching is too narrow and strains the wrists.','Tuck elbows in throughout to keep the focus on the triceps.'],
    commonMistakes: ['Gripping too narrow and straining the wrists.','Flaring elbows out.'],
  },

  // ─── LEGS ─────────────────────────────────────────────────────────────────
  {
    name: 'Squat', muscleGroup: 'Legs', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'The king of leg exercises — building quads, glutes, and hamstrings.',
    instructions: ['Position the barbell on your upper traps and step back from the rack.','Stand with feet slightly wider than shoulder-width, toes pointing out 15–30 degrees.','Take a deep breath and brace your core hard.','Initiate the squat by pushing your knees out and sitting your hips back and down.','Descend until your thighs are at least parallel to the floor.','Drive through your heels to stand back up, keeping chest tall.'],
    tips: ['Keep your chest up and spine neutral throughout.','Push your knees out in the direction of your toes.','Go to at least parallel for full muscle development.','Wear flat shoes or squat barefoot for better stability.'],
    commonMistakes: ['Knees caving inward — push them out.','Not reaching parallel depth.','Heels rising off the floor.','Leaning too far forward.'],
  },
  {
    name: 'Leg Press', muscleGroup: 'Legs', equipment: 'Machine', difficulty: 'Beginner',
    description: 'A machine-based lower body press suitable for beginners and high-volume training.',
    instructions: ['Sit in the machine with your back and head flat against the pad.','Place feet shoulder-width apart on the platform.','Release the safety handles.','Lower the platform by bending your knees toward your chest.','Stop when knees form a 90-degree angle.','Press the platform back up without locking out your knees.'],
    tips: ['Higher foot placement targets glutes and hamstrings more.','Lower foot placement targets quads more.','Never fully lock out your knees at the top.'],
    commonMistakes: ['Locking out the knees at the top.','Knees caving inward.','Lifting hips off the pad at the bottom.'],
  },
  {
    name: 'Romanian Deadlift', muscleGroup: 'Legs', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'A hip hinge movement targeting the hamstrings and glutes with a deep stretch.',
    instructions: ['Stand holding the barbell in front of your thighs, shoulder-width grip.','Keep a slight bend in your knees — this stays constant throughout.','Hinge at the hips, pushing them back as you lower the bar along your legs.','Lower until you feel a deep stretch in your hamstrings.','Drive your hips forward to return to standing.','Squeeze your glutes hard at the top.'],
    tips: ['Keep the bar close to your body throughout.','Focus on feeling the stretch in the back of your thighs.','The movement is in the hips — not the knees.'],
    commonMistakes: ['Rounding the lower back.','Bending the knees too much.','Not hinging deep enough to feel the hamstring stretch.'],
  },
  {
    name: 'Lunge', muscleGroup: 'Legs', equipment: 'None', difficulty: 'Beginner',
    description: 'A unilateral leg exercise that builds quad, glute, and balance simultaneously.',
    instructions: ['Stand with feet together and hands on hips.','Take a large step forward with one foot.','Lower your back knee toward the floor until both knees form 90-degree angles.','Your front knee should stay above your ankle.','Push off your front foot to return to standing.','Alternate legs each rep.'],
    tips: ['Take a big enough step so your front shin stays vertical.','Keep your torso upright — do not lean forward.','Add dumbbells for extra resistance.'],
    commonMistakes: ['Front knee going past the toes.','Leaning the torso too far forward.','Not lowering enough — get the back knee close to the floor.'],
  },
  {
    name: 'Calf Raise', muscleGroup: 'Legs', equipment: 'None', difficulty: 'Beginner',
    description: 'A simple isolation exercise for building calf size and ankle stability.',
    instructions: ['Stand with feet hip-width apart, toes pointing forward.','Slowly rise onto your toes as high as possible.','Pause at the top and squeeze your calves.','Lower slowly back down, going below starting height if on a step.'],
    tips: ['Do these on the edge of a step for greater range of motion.','Slow 3-second lowering phase builds more muscle.','Calves respond well to high reps (15–30).'],
    commonMistakes: ['Not getting full range of motion.','Rushing through reps.'],
  },
  {
    name: 'Hip Thrust', muscleGroup: 'Legs', equipment: 'Barbell', difficulty: 'Intermediate',
    description: 'The most effective exercise for glute development, with superior muscle activation over squats and deadlifts.',
    instructions: ['Sit on the floor with your upper back against a bench, barbell across your hips.','Plant feet flat on the floor, hip-width apart.','Brace your core and drive through your heels.','Thrust your hips upward until your body forms a straight line from knees to shoulders.','Squeeze your glutes as hard as possible at the top.','Lower your hips back down with control.'],
    tips: ['Use a barbell pad to protect your hips.','At the top, your shin should be vertical — adjust foot position if not.','Squeeze the glutes at the top for at least a full second.'],
    commonMistakes: ['Not reaching full hip extension — push all the way up.','Letting the back arch excessively — keep ribs down.','Feet too far away or too close — shins should be vertical at top.'],
  },
  {
    name: 'Leg Curl', muscleGroup: 'Legs', equipment: 'Machine', difficulty: 'Beginner',
    description: 'The primary hamstring isolation exercise targeting the back of the thigh.',
    instructions: ['Adjust the machine so the pad rests just above your heels.','Lie face down with your knees just off the edge of the pad.','Curl your heels toward your glutes by contracting your hamstrings.','Pause and squeeze at the peak.','Slowly lower back to the starting position.'],
    tips: ['Point your toes slightly to emphasize the hamstrings.','Do not let your hips rise off the pad — keep them flat.','Slow the lowering phase for extra hamstring work.'],
    commonMistakes: ['Using too much weight and letting hips rise.','Not achieving full range of motion.','Rushing through reps — control both directions.'],
  },
  {
    name: 'Leg Extension', muscleGroup: 'Legs', equipment: 'Machine', difficulty: 'Beginner',
    description: 'The primary quadriceps isolation exercise for building front thigh size and definition.',
    instructions: ['Sit in the machine with your back flat and feet hooked under the pad.','Adjust the seat so your knees align with the machine pivot.','Extend your legs by straightening your knees until fully extended.','Squeeze your quads hard at the top.','Slowly lower back to 90 degrees.'],
    tips: ['Control the lowering phase — the negative builds just as much muscle.','A full squeeze at the top is key for quad activation.','Not ideal as the only quad exercise — pair with squats or leg press.'],
    commonMistakes: ['Going too heavy and using momentum.','Not fully extending the knees.','Lowering the weight too quickly.'],
  },
  {
    name: 'Bulgarian Split Squat', muscleGroup: 'Legs', equipment: 'Dumbbells', difficulty: 'Intermediate',
    description: 'One of the most effective single-leg exercises for quad and glute development.',
    instructions: ['Stand in front of a bench and place one foot behind you on it.','Hold dumbbells at your sides.','Lower your back knee toward the ground by bending your front knee.','Keep your front shin as vertical as possible.','Drive back up through your front heel to the starting position.','Complete all reps on one side before switching.'],
    tips: ['Position your front foot far enough forward so your shin stays vertical.','This will expose single-leg weaknesses and improve balance over time.','Start with bodyweight before adding dumbbells.'],
    commonMistakes: ['Front foot too close to the bench — causes the knee to travel too far forward.','Leaning too far forward.','Dropping the back knee too fast without control.'],
  },
  {
    name: 'Goblet Squat', muscleGroup: 'Legs', equipment: 'Dumbbells', difficulty: 'Beginner',
    description: 'A beginner-friendly squat variation that naturally promotes good squat mechanics.',
    instructions: ['Hold a dumbbell vertically in front of your chest with both hands.','Stand with feet slightly wider than shoulder-width, toes turned out.','Squat down, keeping elbows inside your knees as you descend.','Reach parallel or below if mobility allows.','Drive back up to the starting position.'],
    tips: ['The counterbalance of the dumbbell makes it easier to stay upright.','Great teaching tool for squat mechanics before adding a barbell.','Focus on pushing knees out and keeping your chest tall.'],
    commonMistakes: ['Letting the knees cave inward.','Not reaching squat depth.','Holding the dumbbell too low.'],
  },
  {
    name: 'Glute Bridge', muscleGroup: 'Legs', equipment: 'None', difficulty: 'Beginner',
    description: 'A bodyweight glute activation exercise and excellent alternative to the hip thrust.',
    instructions: ['Lie on your back with knees bent and feet flat on the floor.','Place feet hip-width apart about 12 inches from your glutes.','Drive through your heels and squeeze your glutes to lift your hips.','Raise until your body forms a straight line from knees to shoulders.','Hold the top position for 1–2 seconds, squeezing hard.','Lower slowly back to the floor.'],
    tips: ['Drive your knees outward to activate the glutes more.','Add a resistance band above the knees or a weight plate on the hips to progress.'],
    commonMistakes: ['Feet too far away — you should feel it in your glutes, not hamstrings.','Not squeezing the glutes at the top.','Letting hips sag in the middle.'],
  },
  {
    name: 'Hack Squat', muscleGroup: 'Legs', equipment: 'Machine', difficulty: 'Intermediate',
    description: 'A machine squat variation allowing heavy loading with quad emphasis and less lower back stress.',
    instructions: ['Step into the hack squat machine and position your shoulders under the pads.','Place feet shoulder-width on the platform, toes slightly out.','Release the safety handles.','Lower yourself by bending your knees until thighs are parallel.','Press through your heels to return to the starting position.','Re-engage safety handles at the end of your set.'],
    tips: ['A lower foot position emphasizes quads; higher emphasizes glutes and hamstrings.','Great option when your lower back is fatigued from deadlifts.'],
    commonMistakes: ['Not hitting parallel depth.','Letting knees cave in.','Locking out the knees completely at the top.'],
  },
  {
    name: 'Box Jump', muscleGroup: 'Legs', equipment: 'None', difficulty: 'Intermediate',
    description: 'A plyometric exercise building explosive leg power and athleticism.',
    instructions: ['Stand in front of a sturdy box with feet shoulder-width apart.','Dip into a quarter squat and swing your arms back.','Explosively jump, swinging your arms forward and pulling your knees up.','Land softly on top of the box with both feet flat.','Step down carefully — do not jump down.','Reset and repeat.'],
    tips: ['Land as softly as possible — a loud landing means too much impact.','Build up box height gradually.','Focus on the explosion from the ground more than how high you jump.'],
    commonMistakes: ['Landing with stiff legs — absorb with bent knees.','Jumping down from the box rather than stepping.','Starting too high a box before mastering the movement.'],
  },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  {
    name: 'Plank', muscleGroup: 'Core', equipment: 'None', difficulty: 'Beginner',
    description: 'The foundational isometric core exercise for building stability and endurance.',
    instructions: ['Start face-down, resting on your forearms and toes.','Elbows should be directly under your shoulders.','Lift your body in a straight line from head to heels.','Squeeze your abs, glutes, and quads — full body tension.','Hold for the desired duration.'],
    tips: ['If your hips sag, reduce the duration.','Breathe steadily — do not hold your breath.','For extra difficulty, try lifting one leg or one arm.'],
    commonMistakes: ['Hips sagging toward the floor.','Hips piked up too high.','Holding breath instead of breathing normally.'],
  },
  {
    name: 'Crunch', muscleGroup: 'Core', equipment: 'None', difficulty: 'Beginner',
    description: 'A classic abdominal exercise targeting the rectus abdominis (six-pack muscles).',
    instructions: ['Lie on your back with knees bent and feet flat on the floor.','Place fingertips lightly behind your ears — do not pull on your neck.','Exhale and curl your upper body toward your knees.','Only your shoulder blades should lift off the floor.','Slowly lower back down.'],
    tips: ['Focus on the contraction — this is a small movement, not a sit-up.','Exhale forcefully at the top for more activation.'],
    commonMistakes: ['Pulling on the neck with your hands.','Using momentum to swing up.'],
  },
  {
    name: 'Russian Twist', muscleGroup: 'Core', equipment: 'None', difficulty: 'Intermediate',
    description: 'A rotational core exercise targeting the obliques and improving rotational strength.',
    instructions: ['Sit on the floor with knees bent and feet slightly off the ground.','Lean back slightly to a 45-degree angle.','Clasp your hands together or hold a weight.','Rotate your torso to the right, bringing your hands toward the floor.','Rotate to the left in a controlled manner.'],
    tips: ['Rotate from your torso, not just your arms.','Add a medicine ball or dumbbell to increase resistance.'],
    commonMistakes: ['Moving only the arms without rotating the torso.','Letting your back round excessively.'],
  },
  {
    name: 'Leg Raise', muscleGroup: 'Core', equipment: 'None', difficulty: 'Intermediate',
    description: 'Targets the lower abs and hip flexors by lifting the legs from a lying position.',
    instructions: ['Lie flat on your back with arms at your sides or under your glutes.','Keep legs together and straight.','Lift your legs to 90 degrees by contracting your abs.','Lower them slowly back down.','Stop just before your heels touch the floor and repeat.'],
    tips: ['Press your lower back into the floor to protect your spine.','The slower you lower, the more effective.','If too hard, bend your knees slightly.'],
    commonMistakes: ['Letting the lower back arch away from the floor.','Dropping legs quickly.'],
  },
  {
    name: 'Mountain Climber', muscleGroup: 'Core', equipment: 'None', difficulty: 'Intermediate',
    description: 'A dynamic core exercise that also elevates the heart rate for a cardio benefit.',
    instructions: ['Start in a high plank position with arms straight.','Keep your hips level and core tight.','Drive one knee toward your chest quickly.','Return it and immediately drive the other knee forward.','Alternate rapidly, maintaining a strong plank position.'],
    tips: ['Keep your hips down — do not let them pike up.','The faster you go, the more cardio benefit.'],
    commonMistakes: ['Hips rising up.','Losing the plank position in the upper body.'],
  },
  {
    name: 'Side Plank', muscleGroup: 'Core', equipment: 'None', difficulty: 'Beginner',
    description: 'An isometric lateral core exercise targeting the obliques and improving lateral stability.',
    instructions: ['Lie on your side and prop yourself up on one forearm.','Stack your feet or stagger them for balance.','Lift your hips until your body forms a straight line from head to feet.','Squeeze your obliques and hold the position.','Keep your hips up — do not let them sag.','Switch sides after completing your time.'],
    tips: ['Stack or slightly stagger feet for stability.','Drive your hip up toward the ceiling for a stronger oblique contraction.'],
    commonMistakes: ['Hips sagging down.','Rolling the body forward or backward.'],
  },
  {
    name: 'Hanging Leg Raise', muscleGroup: 'Core', equipment: 'Pull-up Bar', difficulty: 'Advanced',
    description: 'A demanding ab exercise performed from a dead hang that targets the lower abs and hip flexors.',
    instructions: ['Hang from a pull-up bar with arms fully extended and an overhand grip.','Engage your core to prevent swinging.','Raise your legs together by curling your hips and contracting your abs.','Bring your legs to horizontal or above — the higher, the harder.','Slowly lower your legs back to the starting position.','Avoid swinging.'],
    tips: ['Initiate the movement from your core, not your hip flexors.','Curling the pelvis under at the top greatly increases abs activation.','Bend the knees to make it easier as you build strength.'],
    commonMistakes: ['Swinging the legs with momentum.','Not controlling the descent.','Letting the lower back arch excessively.'],
  },
  {
    name: 'Ab Wheel Rollout', muscleGroup: 'Core', equipment: 'Ab Wheel', difficulty: 'Advanced',
    description: 'One of the most demanding core exercises, building anti-extension strength across the entire core.',
    instructions: ['Kneel on the floor gripping the ab wheel with both hands.','Start with the wheel under your shoulders.','Slowly roll the wheel forward, extending your body toward the floor.','Reach as far as you can while maintaining a straight body.','Pull the wheel back to the starting position by contracting your abs and lats.'],
    tips: ['Start with partial rollouts if a full rollout is too difficult.','Keep your core braced throughout — do not let your lower back sink.','This exercise taxes both the abs and lats significantly.'],
    commonMistakes: ['Letting the lower back arch and collapse to the floor.','Using only the arms — the pull back must come from the core.'],
  },
  {
    name: 'Dead Bug', muscleGroup: 'Core', equipment: 'None', difficulty: 'Beginner',
    description: 'An anti-extension core exercise that teaches coordination and protects the lower back.',
    instructions: ['Lie on your back with arms pointing straight up and knees bent at 90 degrees.','Press your lower back firmly into the floor — it must stay there.','Slowly lower your right arm overhead while extending your left leg.','Stop just before your back lifts off the floor.','Return to the starting position and repeat on the opposite side.'],
    tips: ['The key is keeping your lower back glued to the floor throughout.','Move slowly — control is the entire point of this exercise.','Great for people with lower back issues.'],
    commonMistakes: ['Letting the lower back arch away from the floor.','Moving too fast and losing coordination.'],
  },
  {
    name: 'Bicycle Crunch', muscleGroup: 'Core', equipment: 'None', difficulty: 'Beginner',
    description: 'A dynamic crunch variation that activates both the rectus abdominis and obliques.',
    instructions: ['Lie on your back with hands lightly behind your head.','Lift your shoulders off the ground and bring your knees to 90 degrees.','Rotate your right elbow toward your left knee while extending your right leg.','Immediately rotate the other way — left elbow to right knee.','Continue in a controlled cycling motion.'],
    tips: ['Rotate from your torso — your elbow does not need to touch your knee.','Keep the pace controlled — slow is more effective than fast for this exercise.'],
    commonMistakes: ['Pulling on the neck with the hands.','Moving only the elbows rather than rotating the torso.'],
  },

  // ─── CARDIO ───────────────────────────────────────────────────────────────
  {
    name: 'Running', muscleGroup: 'Cardio', equipment: 'None', difficulty: 'Beginner',
    description: 'The most accessible cardio exercise for improving cardiovascular fitness and burning calories.',
    instructions: ['Start with a 5-minute brisk walk to warm up.','Maintain an upright posture with a slight forward lean.','Land with your foot under your hips, not in front of your body.','Keep your arms at 90 degrees and swing forward.','Breathe rhythmically — inhale for 2 steps, exhale for 2 steps.','Cool down with a 5-minute walk.'],
    tips: ['Talk test: if you can hold a conversation, you are at a good aerobic pace.','Start with run/walk intervals if you are a beginner.','Increase weekly distance by no more than 10% per week.'],
    commonMistakes: ['Overstriding — landing with foot too far in front.','Starting too fast and burning out early.'],
  },
  {
    name: 'Cycling', muscleGroup: 'Cardio', equipment: 'Bike', difficulty: 'Beginner',
    description: 'A low-impact cardio exercise that is easy on the joints while building endurance.',
    instructions: ['Adjust the seat so your knee has a slight bend at the bottom of the pedal stroke.','Start at a comfortable resistance and warm up for 5 minutes.','Pedal in smooth circles rather than just pushing down.','Maintain a cadence of 60–90 RPM for aerobic fitness.'],
    tips: ['Low impact makes cycling great for people with knee or hip issues.','Interval training on a bike burns more calories.'],
    commonMistakes: ['Seat too low — causes knee strain.','Bouncing on the seat.'],
  },
  {
    name: 'Jump Rope', muscleGroup: 'Cardio', equipment: 'Jump Rope', difficulty: 'Beginner',
    description: 'An excellent calorie-burning cardio exercise that improves coordination and footwork.',
    instructions: ['Hold the rope handles at hip height with elbows slightly bent.','Jump just high enough to clear the rope — 1 to 2 inches off the ground.','Land softly on the balls of your feet.','Keep jumps small and consistent.'],
    tips: ['Start with 30 seconds on, 30 seconds rest intervals.','Keep wrists relaxed — rotation comes from wrists, not arms.'],
    commonMistakes: ['Jumping too high — wasted energy.','Using the whole arm to rotate instead of just the wrist.'],
  },
  {
    name: 'Walking', muscleGroup: 'Cardio', equipment: 'None', difficulty: 'Beginner',
    description: 'The most beginner-friendly form of cardio — low impact, sustainable, and effective for fat loss.',
    instructions: ['Stand tall with head up and shoulders back.','Swing your arms naturally with a slight bend in the elbows.','Strike the ground with your heel and roll to the toe.','Maintain a pace that is brisk but still comfortable for conversation.','Aim for 30–60 minutes of continuous walking.'],
    tips: ['Adding incline (hills or treadmill incline) greatly increases calorie burn.','Aim for 7,000–10,000 steps daily for general health.','Great for active recovery between intense training days.'],
    commonMistakes: ['Slouching the shoulders forward.','Looking down at the ground instead of ahead.'],
  },
  {
    name: 'Swimming', muscleGroup: 'Cardio', equipment: 'None', difficulty: 'Intermediate',
    description: 'A full-body, zero-impact cardio exercise excellent for cardiovascular fitness and recovery.',
    instructions: ['Start with a slow warm-up lap at a relaxed pace.','Focus on body position — stay horizontal and streamlined.','Use alternating arm strokes and kick your legs continuously.','Breathe on every second or third stroke — turn your head to the side.','Aim for continuous laps, resting at the wall as needed.'],
    tips: ['Learning proper technique is essential to make swimming effective.','The freestyle stroke is the most efficient for fitness swimming.','Pull buoys and kick boards help practice isolated technique.'],
    commonMistakes: ['Lifting the head too high to breathe — causes hips to sink.','Not fully extending the arm on entry.'],
  },
  {
    name: 'Rowing Machine', muscleGroup: 'Cardio', equipment: 'Rowing Machine', difficulty: 'Beginner',
    description: 'A full-body, low-impact cardio machine that works the legs, back, and arms simultaneously.',
    instructions: ['Sit with feet strapped in and grab the handle.','Start with legs bent and arms extended — the catch position.','Drive through your legs first — push with 60% of the force.','Once legs are nearly straight, lean back slightly and pull the handle to your lower chest.','Reverse the order: extend arms, lean forward, bend knees to return.'],
    tips: ['The drive order is critical: Legs → Lean → Arms. Return is reverse: Arms → Lean → Legs.','Maintain an upright posture during the drive — do not hunch.','Set the damper to 3–5 for most cardio work.'],
    commonMistakes: ['Pulling with the arms first — legs should initiate the drive.','Hunching the back.','Using too high a damper setting.'],
  },
  {
    name: 'Elliptical', muscleGroup: 'Cardio', equipment: 'Elliptical Machine', difficulty: 'Beginner',
    description: 'A low-impact cardio machine mimicking running without the joint stress — great for beginners and recovery.',
    instructions: ['Step onto the pedals and grip the handlebars.','Begin pedaling in a smooth elliptical motion.','Keep a tall posture — do not lean forward on the handles.','Push and pull the handlebars to engage your upper body.','Maintain a moderate, sustainable pace.'],
    tips: ['Using the handles actively turns this into a full-body workout.','Reversing the pedal direction targets different muscles.','Resistance and incline add intensity without increasing impact.'],
    commonMistakes: ['Leaning on the handlebars and offloading your weight.','Going at the same resistance for the entire workout — vary it.'],
  },
  {
    name: 'Sprint Intervals', muscleGroup: 'Cardio', equipment: 'None', difficulty: 'Advanced',
    description: 'High-intensity interval training using maximum-effort sprints for superior fat burning and fitness.',
    instructions: ['Warm up with 5–10 minutes of easy jogging.','Sprint at maximum effort for 20–30 seconds.','Walk or jog slowly for 60–90 seconds to recover.','Repeat the sprint-recovery cycle 6–10 times.','Cool down with 5 minutes of easy walking.'],
    tips: ['True sprinting means giving absolute maximum effort — not 80%.','The rest period is as important as the sprint — do not cut it short.','Start with just 4–6 intervals and build up over weeks.'],
    commonMistakes: ['Not sprinting hard enough — it must be near-maximal effort.','Skipping the warm-up — increases injury risk significantly.','Too many intervals before building a base.'],
  },

  // ─── FULL BODY ────────────────────────────────────────────────────────────
  {
    name: 'Burpee', muscleGroup: 'Full Body', equipment: 'None', difficulty: 'Advanced',
    description: 'A full-body conditioning exercise combining a squat, plank, push-up, and jump.',
    instructions: ['Stand with feet shoulder-width apart.','Squat down and place your hands on the floor.','Jump your feet back to a plank position.','Perform a push-up.','Jump your feet back toward your hands.','Explosively jump up with arms overhead.','Land softly and immediately begin the next rep.'],
    tips: ['Focus on linking movements smoothly rather than going fast.','Modify by stepping instead of jumping if needed.'],
    commonMistakes: ['Sagging hips in the plank position.','Not fully extending the jump at the top.','Skipping the push-up.'],
  },
  {
    name: 'Kettlebell Swing', muscleGroup: 'Full Body', equipment: 'Kettlebell', difficulty: 'Intermediate',
    description: 'A powerful hip-hinge exercise that builds explosive power in the posterior chain.',
    instructions: ['Stand with feet slightly wider than shoulder-width, kettlebell on the floor.','Hinge at the hips and grip the kettlebell with both hands.','Hike the kettlebell back between your legs.','Drive your hips forward explosively to swing the kettlebell to chest height.','Let gravity bring it back between your legs while hinging at the hips.','The movement is a hip hinge — NOT a squat.'],
    tips: ['Power comes from the hips — not from your arms or shoulders.','At the top, stand tall and squeeze your glutes.','Start light to master the hip hinge pattern first.'],
    commonMistakes: ['Squatting the movement instead of hinging.','Using the arms to pull the bell up.','Letting the lower back round.'],
  },
  {
    name: 'Battle Ropes', muscleGroup: 'Full Body', equipment: 'Battle Ropes', difficulty: 'Intermediate',
    description: 'An intense full-body conditioning exercise building muscular endurance and cardiovascular fitness.',
    instructions: ['Anchor the ropes and grab one end in each hand.','Stand with feet shoulder-width apart and knees slightly bent.','Create waves by alternating arm slams up and down rapidly.','Keep your core engaged and back straight.','Aim for 20–40 second continuous bouts with short rests.'],
    tips: ['Keep the waves consistent — do not let them die.','Vary your pattern: alternating waves, simultaneous slams, circles.','Stand closer to the anchor for more resistance.'],
    commonMistakes: ['Using only the arms — drive motion from your whole body.','Letting the ropes go slack.'],
  },
  {
    name: 'Farmers Carry', muscleGroup: 'Full Body', equipment: 'Dumbbells', difficulty: 'Intermediate',
    description: 'A loaded carry exercise building grip strength, core stability, and full-body conditioning.',
    instructions: ['Pick up a heavy dumbbell or kettlebell in each hand.','Stand tall with shoulders back and core braced.','Walk in a straight line for the prescribed distance or time.','Keep steps controlled and deliberate — do not rush.','Set the weights down with control.'],
    tips: ['Keep your shoulders level — do not let them shrug up.','A tight core prevents the weights from pulling your torso sideways.','Start heavy — this exercise is meant to be challenging.'],
    commonMistakes: ['Leaning to one side.','Letting the shoulders round forward.','Taking too many small choppy steps.'],
  },
  {
    name: 'Clean and Press', muscleGroup: 'Full Body', equipment: 'Barbell', difficulty: 'Advanced',
    description: 'An Olympic-style lift combining a power clean and overhead press for full-body power development.',
    instructions: ['Stand with feet hip-width apart and the barbell over mid-foot.','Hinge and grip the bar at shoulder width.','Pull the bar explosively, extending your hips, knees, and ankles simultaneously.','As the bar reaches chest height, drop under and catch it on your front shoulders.','From the catch position, press the bar overhead until arms are locked out.','Lower the bar back to the floor under control.'],
    tips: ['The clean and press combines multiple complex movement patterns — learn each separately first.','Use light weight to master the technique before adding load.'],
    commonMistakes: ['Using the arms to pull instead of the legs and hips.','Catching the bar too far in front.','Pressing without stabilizing the catch first.'],
  },
  {
    name: 'Medicine Ball Slam', muscleGroup: 'Full Body', equipment: 'Medicine Ball', difficulty: 'Intermediate',
    description: 'A full-body power exercise that trains explosive force production and serves as a stress reliever.',
    instructions: ['Stand with feet shoulder-width apart holding a medicine ball.','Raise the ball overhead with both hands, rising onto your toes.','Slam the ball into the ground as hard as possible.','Hinge at the hips and bend your knees as you slam.','Pick the ball up on the bounce and immediately repeat.'],
    tips: ['Engage your entire body — not just your arms — during the slam.','Let out a grunt or exhale forcefully for maximum power.','Use a ball that does not bounce too high for safety.'],
    commonMistakes: ['Using only the arms.','Not following through with the hips and core.','Standing too tall — hinge your hips on the way down.'],
  },
];